kind: Service
apiVersion: v1
metadata:
  name: geoserver-service
spec:
  type: NodePort
  selector:
    app: geoserver
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31312
    name: geoserver-port
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: geoserver-pv
spec:
  capacity:
    storage: 10G
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/max/dbpro/geoserver
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dell-t5610
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-pvc
  labels:
    app: geoserver
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  volumeName: geoserver-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoserver-deployment
  labels:
    app: geoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
  template:
    metadata:
      labels:
        app: geoserver
    spec:
      containers:
      - name: geoserver-container
        image: kartoza/geoserver:latest
        env:
        - name: USERNAME
          value: "geouser"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: geoserver-secret
              key: password
        - name: GEOSERVER_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: geoserver-secret
              key: admin-password
        volumeMounts:
        - mountPath: /opt/geoserver/data_dir
          name: geoserver-volume
      volumes:
      - name: geoserver-volume
        persistentVolumeClaim:
          claimName: geoserver-pvc
