kind: Service
apiVersion: v1
metadata:
  name: postgis-service
spec:
  type: NodePort
  selector:
    app: postgis
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 31313
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgis-pv
spec:
  capacity:
    storage: 40G
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/max/dbpro/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dell-t5610
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-pvc
  labels:
    app: postgis
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: postgis-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis-deployment
  labels:
    app: postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
      - name: postgis-container
        image: mdillon/postgis:11-alpine
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgis-secret
              key: password
        - name: POSTGRES_DB
          value: geospatial
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgis-volume
      volumes:
      - name: postgis-volume
        persistentVolumeClaim:
          claimName: postgis-pvc
